# Generated by Django 3.0 on 2022-10-03 18:54

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Folio')),
                ('estado', models.CharField(blank=True, choices=[('En Curso', 'En Curso'), ('Observación', 'Observación'), ('Resuelto', 'Resuelto'), ('Pendiente', 'Pendiente')], default='En Curso', max_length=45, null=True, verbose_name='Estado')),
                ('msr', models.CharField(blank=True, choices=[('AM', 'AM'), ('BAF', 'BAF'), ('CL/EX', 'CL/EX'), ('CS', 'CS'), ('CX', 'CX'), ('DX', 'DX'), ('TX', 'TX')], max_length=45, null=True, verbose_name='MSR')),
                ('noti', models.CharField(blank=True, choices=[('MCO', 'MCO'), ('SUBTEL', 'SUBTEL'), ('DS60-SUBTEL', 'DS60-SUBTEL'), ('CLTS_VIP', 'CLTS_VIP')], max_length=45, null=True, verbose_name='NOT')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Descripción')),
                ('nemonico', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nemónico')),
                ('region', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII'), ('XIII', 'XIII'), ('XIV', 'XIV'), ('XV', 'XV'), ('XVI', 'XVI')], max_length=45, null=True, verbose_name='Región')),
                ('inicio_afectacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio de Afectación')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Duración')),
                ('ultima_actualizacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
                ('proxima_actualizacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Próxima Actualización')),
                ('calendarizacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Calendarización')),
                ('tiempo_excedido', models.DurationField(default=datetime.timedelta(0), verbose_name='Tiempo Excedido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IncideciaHijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Folio')),
                ('estado', models.CharField(blank=True, choices=[('En Curso', 'En Curso'), ('Observación', 'Observación'), ('Resuelto', 'Resuelto'), ('Pendiente', 'Pendiente')], default='En Curso', max_length=45, null=True, verbose_name='Estado')),
                ('msr', models.CharField(blank=True, choices=[('AM', 'AM'), ('BAF', 'BAF'), ('CL/EX', 'CL/EX'), ('CS', 'CS'), ('CX', 'CX'), ('DX', 'DX'), ('TX', 'TX')], max_length=45, null=True, verbose_name='MSR')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nemonico', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nemónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_incidencia_padres', to='bitacora.Incidencia')),
            ],
            options={
                'verbose_name': 'Incidencia Hijo',
                'verbose_name_plural': 'Incidencias Hijos',
                'ordering': ['-created'],
            },
        ),
    ]
