# Generated by Django 3.0 on 2022-10-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True, verbose_name='Folio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nemonico', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nemónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='elemento',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII'), ('XIII', 'XIII'), ('XIV', 'XIV'), ('XV', 'XV'), ('XVI', 'XVI')], max_length=45, null=True, verbose_name='Región'),
        ),
    ]
