# Generated by Django 3.0 on 2022-10-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_auto_20221004_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='elemento',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='elemento',
            field=models.ManyToManyField(blank=True, related_name='get_elementos', to='bitacora.Elemento', verbose_name='Guardia'),
        ),
    ]
