# Generated by Django 3.0 on 2022-10-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_auto_20221004_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='calendarizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Calendarización'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='elemento',
            field=models.ManyToManyField(blank=True, related_name='get_elementos', to='bitacora.Elemento', verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='proxima_actualizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próxima Actualización'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización'),
        ),
    ]
