# Generated by Django 3.0 on 2022-10-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0005_auto_20221005_1812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elemento',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='incideciahijo',
            unique_together={('folio',)},
        ),
        migrations.AlterUniqueTogether(
            name='incidencia',
            unique_together={('folio',)},
        ),
    ]
